project:
  type: website
  # pre-render: ./register-all-kernels.sh # This option is if you are trying to get quarto to re-run the notebooks (which will require their kernels to be registered)
  output-dir: docs

execute:
  engine: jupyter

website:
  description: "Sam Hurst's Codefolio Portal"
  site-url: https://samuelrhurst.github.io/codefolio-portal/
  title: "Sam Hurst's Codefolio Portal"
  open-graph: true
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/samuelrhurst
      - icon: linkedin
        href: https://www.linkedin.com/in/samuelrhurst/
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
